site_name: EGroups Documentation
site_author: Joshua Maglione
copyright: "&copy; 2023 J. Maglione"
nav:
    - Home: index.md
    - Constructors: constructors.md
    - Isomorphism: isomorphism.md
theme:
    name: mkdocs
    custom_dir: custom_theme/
